### ISSUE TITLE
timestamps.json is randomly corrupted

### ISSUE THREAD

**Issue by MMulthaupt** [setlog/trivrost#264]
timestamps.json is sometimes corrupted, containing a bunch of NULL bytes. We made [a workaround](https://github.com/setlog/trivrost/pull/237) to prevent this from spawning support requests with the next release, but we should still try to fix the cause.

**Comment by MMulthaupt** [comment]
The cause of the problem is this line:

https://github.com/setlog/trivrost/blob/ecbdfe0fd807e7b530e86af9e3976b6367f76373/pkg/launcher/timestamps/timestamps.go#L57

It turns out that closing a file can fail even though all prior writes were successful. To my understanding, the reason for this is part of the secret sauce of the OS developers. Regardless, when unsuccessfully closing a file after successful writes one should assume the entire file is now garbage (which is what we are seeing). The workaround we made still makes sense, because without a call to `file.Sync()` the file could still get corrupted when it is eventually persisted on the hard drive due to hardware failures.

More info on this can be found in this blog post: https://www.joeshaw.org/dont-defer-close-on-writable-files/

It looks like no change is required since we already have a workaround and nobody seems to know what is safe to do and what isn't after such an error has occurred.

@dragetd What do you think?

**Comment by dragetd** [comment]
Super interesting. I also found this stack overflow article: https://stackoverflow.com/questions/64744802/safely-close-a-file-descriptor-in-golang which boils down to what your linked article says.

At least I think it is clear, that using the defer(close) pattern might not be the way to go and we might want to update this to something doing a sync before returning, as the article suggest. But that does not make any difference to what you said, our workaround is still valid.

There is no security implication by this either, since it would only be an issue in the case an attacker has the ability to locally corrupt/manipulate the timestamp file and in this case it is already game over.

BTW, just recently our timestamp mechanism uncovered a configuration issue (two system with the same Vendor/Product combination overwriting each other), so it works beautifully. Just might need a slightly better user-facing message. :)

Thanks for taking a look at this!
