### ISSUE TITLE
Specify 'application' vs. 'binary' vs. 'program' in glossary

### ISSUE THREAD

**Issue by dragetd** [setlog/trivrost#29]
We switched the definition of what we consider a 'binary' vs 'application' vs 'programm' in the config files.

We should write these things down in the glossary, once we agree on how to define them.

**Comment by MMulthaupt** [comment]
I got some time to think about this as I am currently rewriting the documentation. If we need to specify what ***we*** mean by each of those words, we are doing something wrong. Instead of adding them to the glossary, we should stop using them wrong where we do.

Without sugarcoating:
* A **binary** is a file containing instructions (which just happens to be an executable (i.e. not a library) whenever we refer to one in *this* project)
* An **executable** is something which I can run by double-clicking it in the OS's default file browser or by invoking `./thefile` from the command line. It's likely to be a binary, but can also be other things, e.g. a MacOS `.app`-bundle.
* A **program** is something for which there exists an executable somewhere.
* An **application** is either a glorified program or something which runs in a browser. It's commonly used in customer-facing terminology when marketing software.

The way I see it, the weak link here is that on MacOS both binaries and folders can be executables, depending on what's inside and in their name. GoLang standard library to the rescue: `os.Executable()` returns the path to the executing **binary**, even if it was started from an `.app`-bundle.

Thus I propose:
* Change all occurences of "binary" to "executable".
  * Cover our asses by mentioning we derive this nomenclature from the Go standard library.
* Use "program" when referring to the summation of an executable and its resources, i.e. its `.app`-bundle under MacOS and its ~binary~ executable everywhere else.
* Use "application" when referring to what trivrost launches, but only in high-level documentation artifacts such as `README.md`.

**Comment by dragetd** [comment]
Sure, go ahead with #42 . Fine with me.

**Comment by MMulthaupt** [comment]
There is one problem with using the word "program". E.g. the following phrase from CHANGES.md
> if trivrost finds a folder called `systembundles` next to its binary, it will consider itself installed

(which currently is factually incorrect) would change to:
> if trivrost finds a folder called `systembundles` next to its program, it will consider itself installed

which sounds as if the program was in another place than trivrost, which isn't the case. It's also not self-explanatory. This doesn't seem to solve anything just yet.
