### ISSUE TITLE
System-mode installations should ignore system-bundle updates under certain conditions

### ISSUE THREAD

**Issue by dragetd** [setlog/trivrost#33]
Using the msi-based system-mode installation, an update to a system-bundle forces the user currently to reinstall the MSI with admin privileges.

The whole idea behind the MSI installer is to provide a solution for very restrictive environments. And requiring the admin to update the software immediately - otherwise it will not start - is not the nicest solution.

Current idea: Allow system-mode bundles to be outdated as long as the other bundles are up to date.
The reasoning is, that the system-mode bundles are usually the JRE and the other bundles are the application that is deployed.

**Comment by MMulthaupt** [comment]
Your suggested solution was already put into place a while ago, wherein trivrost only denies execution when both `systembundles` and `bundles` require changes. That still is silly behaviour though.

Here is what I think we should do:
* try to update everything no matter what (system bundles, user bundles, trivrost itself)
* ignore access denied on systembundles and the trivrost binary.
* if by the end of the update process, access to at least one file was denied, show a dialog "Some files could not be updated because doing so requires additional administrative privileges. [Continue anyway](#)"
  * clicking "[Continue anyway](#)" makes trivrost execute commands as normal

This way users can see that taking action is required, but they don't have to deal with it right away. Running as administrator will update protected files, fixing the issue. (Doing so will also download user bundles for the admin user, but that's not critical)

**Comment by MMulthaupt** [comment]
After some discussing we decided the following:
- Never touch systembundles.
  - i.e. do not provoke permission denied errors from the file system.
- Show aforementioned dialog when changes are detected.
- Add a launcher-config setting to specify whether "Continue anyway" should be forbidden.
